[package]
name = "livesplit-core"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[dependencies]
chrono = "0.2.25"
odds = "0.2.25"
serde_json = "0.8.4"
serde_derive = "0.8.21"
serde = "0.8.21"
sxd-document = "0.2.0"
sxd-xpath = "0.4.0"
quick-error = "1.1.0"
base64 = "0.2.1"
try_opt = "0.1.1"
byteorder = "1.0.0"
image = "0.12.1"
